// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Прокошин_Кирилл_ЭФБО_07_23;

#nullable disable

namespace Прокошин_Кирилл_ЭФБО_07_23.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250220103454_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Прокошин_Кирилл_ЭФБО_07_23.Genre", b =>
                {
                    b.Property<int>("genreid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("genreid"));

                    b.Property<string>("genredescr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("genrename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("genreid");

                    b.ToTable("Genres");
                });
#pragma warning restore 612, 618
        }
    }
}
